services:
  neo4j:
    image: neo4j:5.15
    ports:
      - "7692:7474"  # Neo4j Web 界面使用 7692
      - "7693:7687"  # Neo4j Bolt 使用 7693
    environment:
      NEO4J_AUTH: neo4j/qinguoqinchen123
      NEO4J_PLUGINS: '["apoc", "graph-data-science"]'
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

  postgres:
    image: postgres:15
    ports:
      - "5847:5432"  # PostgreSQL 使用 5847
    environment:
      POSTGRES_DB: qinguoqinchen_ai
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qinguoqinchen123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  neo4j_data:
  postgres_data:
  neo4j_logs:
